### PR TITLE
Update and rename 插件主体.cs to mainplugin.cs

### PR DESCRIPTION
**Pull request by Joeljyothish**

### CODE REVIEW

**Comment by ATFGK** [comment]
Thank you for your translation, but those are only documentation comments that have no practical effect.

**Comment by Joeljyothish** [comment]
> Thank you for your translation, but those are only documentation comments that have no practical effect.

It's okay

**Comment by Joeljyothish** [comment]
> Thank you for your translation, but those are only documentation comments that have no practical effect.

Can you release the costom monster plugin please

**Comment by ATFGK** [comment]
> > Thank you for your translation, but those are only documentation comments that have no practical effect.
> 
> Can you release the costom monster plugin please

I think that will soon.

**Comment by Joeljyothish** [comment]
> > > Thank you for your translation, but those are only documentation comments that have no practical effect.
> > 
> > 
> > Can you release the costom monster plugin please
> 
> I think that will soon.

Ok

**Pull request closed without merging**
